### ISSUE TITLE
FR: Focus cursor on `Search Query` input onOpen of modal

### ISSUE THREAD

**Issue by FelipeRearden** [SkepticMystic/advanced-cursors#1]
Hello @SkepticMystic !!!!

## Thank You!

I saw your post on Discord and I jump to my desk to test this amazing plug-in! 

I have been waiting for something like this for a long time: it's exactly what I need !!!!!!!!! 🙏

I'm gonna start to use it in my real workflow and (if you don't mind) I could bring some user suggestions based on my workflow.

## Feature Request

If possible, would be very good if the text cursor (caret) appears in the `Search Query` field after hitting the command from command palette or hotkey.
- This way I don't have to press TAB to get the text caret in the focus of the field :)

---

Thank you very much for making this plug-in :)

I wish you a fantastic day!

**Comment by FelipeRearden** [comment]
Hello @SkepticMystic !!!!

Thank you very for your reply!

> I can totally try doing that! I'll have to learn how to focus elements, but I'm sure it's doable.

Great! Thanks for trying :) I wish you good luck🍀 

I know it's a silly thing, but it's one less keyboard key to press :)

> Also, be do post any other FRs/bugs you find while experimenting with it

Thanks @SkepticMystic ! I will let you know any FRs/bugs that I find :)

---

It's a pleasure to talk to you for the first time! 

I'm getting start to advance my workflow in Obsidian for the past 4 months and I have been watching all of your plug-ins :)
- I'm in that phase to try to understand what I want to/can do with Obsidian.
- Breadcrumbs looks spectacular !!!!!!!!!!!!!!!!!

I just wanna get this opportunity to thank you for everything that you have been doing for our community :)

Let's keep talking! 

Have a great day!

**Comment by SkepticMystic** [comment]
Thanks alot @FelipeRearden, I really appreciate your support 💚 :)
I'm happy to chat about my other plugins, and just in general, too!

Have an awesome day :D
