### ISSUE TITLE
FR: Go further and implement Sublime's "Expand under cursor"

### ISSUE THREAD

**Issue by chrisgrieser** [SkepticMystic/advanced-cursors#2]
Basically, the command takes the text you have selected, searches the next occurrence of it in the text, and creates a second selection of the next occurences. And when you press it again, it creates a third one. It's multi-cursor feature I use the most.

Here is a youtube video that showcases that feature: https://youtu.be/YgEuzl9nnbc?t=45

**Comment by SkepticMystic** [comment]
Indeed! I just need to finish this presentation for tomorrow first 😋
