### ISSUE TITLE
Sidebar panel enable/disable command or setting

### ISSUE THREAD

**Issue by zFrostz** [SkepticMystic/advanced-cursors#20]
Closing the panel and then restarting obsidian makes the panel reappear, ideally there should be a setting or a command to enable the sidebar panel and closing the panel should make it not reappear on restart.
- Provide a setting or command to enable/disable the sidebar panel
- Make it such that the panel remains close after restart when it has been closed manually until re-enabled

**Comment by SkepticMystic** [comment]
I've added a setting for this. It seems to work, but let me know if it gives you issues @zFrostz

**Comment by zFrostz** [comment]
It's working flawlessly so far I'll let you know if I find any issues later on.
