### ISSUE TITLE
[Feature Request] `increment value at each cursor` -> New Settings for TOC

### ISSUE THREAD

**Issue by FelipeRearden** [SkepticMystic/advanced-cursors#22]
Hello @SkepticMystic !!!!!!

I just saw the new command `increment value at each cursor` . it's AMAZING @SkepticMystic  , thank you so much!

If you don't mind, I'd like to suggest two additional settings for the new feature:
- **Setting 1:** option to add the value BEFORE or AFTER the selection instead of overwrite the selection 
- **Setting 2:** option to insert a PREFIX and/or a SUFFIX around the **value** 

## My Workflow:  Numbering Headers 

I have a note that have all my bookmarked tweets imported  from iOS with a shortcut. This is the structure of my note

![BCF7FA3D-2443-4F7D-AC0E-7FA9DFE56B83](https://user-images.githubusercontent.com/85180696/139589049-584d6c55-9eba-4c42-99c5-c4702e50f2bd.jpeg)

I use the headers to separate each tweet. It's much easy to use a `##` because I can see the content on the search panel and using QuickSwitcher++ to navigate between each tweet;
-I transfer these tweets to the related note: For example: if a tweet have a quote from Marcus Aurelius I have a workflow to transfer the selection (tweet) to the note [[Marcus Aurelios]] 

After importing, I fill the header with a number to have a numbered list .

With **Setting 1** I could automate this task. Here is what I'm thinking:

Step 1: My Headings Query `^#.+?\s` -> All;
Step 2: `increment value at each cursor` -> 
- Start= 1 
- Increment= 1 
- `(*)` After 
-  `Sufix` = `.`
- `Prefix` = `Tweet `

This way I have a list like this:

![5146B5BF-D1F0-405B-A4B2-EF50398CA38E](https://user-images.githubusercontent.com/85180696/139589151-de6e66fa-66fc-4144-bad6-87d72e67f417.jpeg)

---

I think we could use this amazing new feature to add easily words in a way to create an personalized TOC :

A few examples: 
Section # -
Chapter #.A -
Lesson 1
Question 1 -> 

The user could create your own lists based on different needs  with these new settings :)
 
---

Thank you very much for reading this! Let me know what you think :)

I wish you a fantastic Sunday!

**Comment by SkepticMystic** [comment]
Hey @FelipeRearden, always good to hear from you :)
Thanks for the detail, I get what you're looking for!

This can be done with the same amount of effort using the base-functionality of existing cursors!

1. Select all headers `^#.+?\s`
3. Move cursors to where you want the number inserted
4. Insert numbers with new function
5. `Ctrl + ←` to move to beginning of number
6. Insert prefix
7. `Ctrl + →` to move to end of number

Writing it out in a list makes it look like alot of work... maybe I can implement some of the features you're requesting, but I think it's helpful to know that it can be done already, you know?

![Imgur](https://imgur.com/GRXdOyE.gif)

**Comment by FelipeRearden** [comment]
> Hey @FelipeRearden, always good to hear from you :)

I have the same feeling @SkepticMystic ! Hello again :)

> This can be done with the same amount of effort using the base-functionality of existing cursors!

Sorry @SkepticMystic ! You are absolutely right !!!!

I didn't notice that we still have multiple cursors after using the `increment value at each cursor` . This way I can do exactly the way you described :) 

Sorry for the misunderstanding. I'm gonna close this issue :)

Have a great day!

**Comment by SkepticMystic** [comment]
No worries, I can definitely make that more clear in the Readme! It helps to hear the experience of someone who didn't write the code:yum:

**Comment by FelipeRearden** [comment]
> No worries, I can definitely make that more clear in the Readme! It helps to hear the experience of someone who didn't write the code:yum:

I read the README @SkepticMystic and I must say that it's crystal clear! 

This case I was biased by my workflow/idea instead of focus on the new command itself :)

Everything is perfect @SkepticMystic :)

Thanks again!
