### ISSUE TITLE
FR: Setting to disable notifications

### ISSUE THREAD

**Issue by mgmeyers** [SkepticMystic/advanced-cursors#25]
This plugin adds one of my most used features from VSCode, `CMD+D`! I would love it, though, if I could disable the notifications that popup when I use this feature and have selected every instance of a selection. As someone with ADHD, notifications are quite jarring and can pull me out of my workflow.

**Comment by SkepticMystic** [comment]
@mgmeyers this should be working in 0.4.3 :)
The setting is enabled by default, so you'll need to toggle it off

**Comment by FelipeRearden** [comment]
> @mgmeyers this should be working in 0.4.3 :)
> The setting is enabled by default, so you'll need to toggle it off

Working on version `0.4.3` Obsidian `0.12.19`
