### ISSUE TITLE
Does not work correctly with Live Preview Mode for insiders.

### ISSUE THREAD

**Issue by newuser127** [SkepticMystic/advanced-cursors#26]
Any plan to update this to work with Live preview mode available to the insiders? Currently it only works if you manually highlight text first and then do your hotkey to jump to next or prior search.

**Comment by SkepticMystic** [comment]
@newuser127 please check if it works in the latest release. My tests are good

**Comment by WhiteNoiseDev** [comment]
works for me

**Comment by TeresaM12** [comment]
Mh maybe I missunderstand but version 0.5.0 is not working for me in Live preview mode (obsidian version 0.13.19). 

I try `^-` with flag m in regex mode using the modal.

- if nothing is selected within the document then nothing happens and the dialog is not closed.
- if I select a text block (everything within it is visible). It finds all the places but in the end it unselects the text block and the special chracters are not highlighted (but the dialog is closed) 
- everything works as expected in legacy editor mode with the same file

Normally when this happens I missed some information ...
Thanks for the great work and your help

**Comment by SkepticMystic** [comment]
@TeresaM12 I see what you mean. Can you try out 0.5.1 and see if this still happens. There is something weird happening with CM6, but it should fail far less often now

**Comment by TeresaM12** [comment]
I tried it (only with the file I used before) and it worked as expected.  Great!
Thanks a lot
