### ISSUE TITLE
[BUG]: Saved Query Commands deletes selection

### ISSUE THREAD

**Issue by chrisgrieser** [SkepticMystic/advanced-cursors#27]
Using the buttons works as intended, using the command from the command palette deletes the selection.

https://user-images.githubusercontent.com/73286100/143858450-65a59dc8-86e7-40c2-a1dc-c9b15443235e.mov

**Comment by SkepticMystic** [comment]
Thanks for the bug report, that seems quite serious.
I know Live Preview isn't actively enabled, but do you have it turned on in settings?

**Comment by SkepticMystic** [comment]
Hmmm I can't reproduce this, and I also can't see why it happens from the code... it's doing the same thing whether you use the buttons or run it from the cmd palette

**Comment by chrisgrieser** [comment]
whatever the reason, it works now. maybe it was related to the other issue and therefore got solved with it? 🤔
