### ISSUE TITLE
BUG: Not working in new editor

### ISSUE THREAD

**Issue by chrisgrieser** [SkepticMystic/advanced-cursors#28]
related to #26, but it also doesn't work in Source Mode, as far as I can tell.

`findUnderWord` probably needs to be updated to CM6, and the sidebar buttons also does not seem to work, too.

**Comment by SkepticMystic** [comment]
@chrisgrieser I believe I've fixed it for CM6. Please give it a try on the latest release and let me know

**Comment by chrisgrieser** [comment]
can confirm, works now 👍
