### ISSUE TITLE
[FR] Insert cursor below/above

### ISSUE THREAD

**Issue by WhiteNoiseDev** [SkepticMystic/advanced-cursors#29]
Hi,
Have you considered adding VScode inspired Insert cursor below and above to your plugin (ctrl-alt-down/up)?

Thanks for your work.

**Comment by SkepticMystic** [comment]
Can do. How exactly does it work, do you know?
If I'm on `line: 4, ch: 7`, and I place a cursor one line up, does it just go to `line: 3, ch: Max(7, line.length)`?

**Comment by WhiteNoiseDev** [comment]
yes, that's what vscode does. This is what happens starting in the middle and doing ctrl-alt-up and ctrl-alt-down

![Animation14](https://user-images.githubusercontent.com/3163647/147852341-5a609e4c-2689-4b09-9b3c-cf304d259371.gif)

**Comment by SkepticMystic** [comment]
@WhiteNoiseDev I've implemented this in 0.5.0, let me know how it works for you :)

**Comment by WhiteNoiseDev** [comment]
it works! :)
